name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "patch | minor | major"
        required: true
        default: "patch"
        options:
          - patch
          - minor
          - major
    branches: [main]

jobs:
  tagging:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
      - name: npm ci
        run: npm ci
      - name : config git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: npm version
        run : |
          NEXT_VERSION=$(npm version ${{ github.event.inputs.version }})
          git add package.json package-lock.json
          git checkout -b version/${NEXT_VERSION}
          git push origin version/${NEXT_VERSION} ${NEXT_VERSION}
          gh pr create --title "bump up version to ${NEXT_VERSION}" --body "This pull request is generated by GitHub Actions" --base main --head version/${NEXT_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}